<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LM0001767" ignored="2" name="Test(failed)" tests="6" failures="6" timestamp="2023-02-15T18:34:42 IST" time="5.123" errors="0">
  <testcase name="verifyHomePageTitleTest" time="1.925" classname="com.JioMart.testCases.TC_001_LoginDDT">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.JioMart.testCases.TC_001_LoginDDT.verifyHomePageTitleTest(TC_001_LoginDDT.java:33)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyHomePageTitleTest -->
  <testcase name="VerifyLoginTest" time="0.001" classname="com.JioMart.testCases.TC_001_LoginDDT">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.JioMart.testCases.TC_001_LoginDDT.VerifyLoginTest(TC_001_LoginDDT.java:64)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- VerifyLoginTest -->
  <testcase name="VerifyLoginTest" time="0.001" classname="com.JioMart.testCases.TC_001_LoginDDT">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.JioMart.testCases.TC_001_LoginDDT.VerifyLoginTest(TC_001_LoginDDT.java:64)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- VerifyLoginTest -->
  <testcase name="VerifyLoginTest" time="0.002" classname="com.JioMart.testCases.TC_001_LoginDDT">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.JioMart.testCases.TC_001_LoginDDT.VerifyLoginTest(TC_001_LoginDDT.java:64)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- VerifyLoginTest -->
  <testcase name="VerifyLoginTest" time="0.002" classname="com.JioMart.testCases.TC_001_LoginDDT">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.JioMart.testCases.TC_001_LoginDDT.VerifyLoginTest(TC_001_LoginDDT.java:64)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- VerifyLoginTest -->
  <testcase name="VerifyLoginTest" time="0.001" classname="com.JioMart.testCases.TC_001_LoginDDT">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.JioMart.testCases.TC_001_LoginDDT.VerifyLoginTest(TC_001_LoginDDT.java:64)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- VerifyLoginTest -->
  <testcase name="VerifyProImage" time="0.0" classname="com.JioMart.testCases.TC_001_LoginDDT">
    <ignored/>
  </testcase> <!-- VerifyProImage -->
  <testcase name="verifyLoginPageTitleTest" time="0.0" classname="com.JioMart.testCases.TC_001_LoginDDT">
    <ignored/>
  </testcase> <!-- verifyLoginPageTitleTest -->
</testsuite> <!-- Test(failed) -->
